[package]
name = "string-calculator"
version = "0.1.0"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
thiserror = "1.0"

[dev-dependencies]
itertools = "0.9"
proptest = "0.10"
